/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import VISTA.Empleado;
import java.awt.Color;

/**
 *
 * @author HP
 */
public class principall extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principall() {
        initComponents();
               this.getContentPane().setBackground(Color.CYAN);
       //centrar el jframe
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmartes = new javax.swing.JButton();
        btnsabado = new javax.swing.JButton();
        btnmiercoles = new javax.swing.JButton();
        btnlunes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnmartes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmartes.setForeground(new java.awt.Color(255, 0, 51));
        btnmartes.setText("MARTES");
        btnmartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmartesActionPerformed(evt);
            }
        });

        btnsabado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsabado.setForeground(new java.awt.Color(153, 0, 0));
        btnsabado.setText("SABADO");
        btnsabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsabadoActionPerformed(evt);
            }
        });

        btnmiercoles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmiercoles.setForeground(new java.awt.Color(204, 0, 0));
        btnmiercoles.setText("MIERCOLES");
        btnmiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmiercolesActionPerformed(evt);
            }
        });

        btnlunes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlunes.setForeground(new java.awt.Color(255, 0, 51));
        btnlunes.setText("LUNES");
        btnlunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlunesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENUS SEGUN CADA DIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnlunes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnmiercoles)
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsabado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmartes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmartes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlunes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsabado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmartesActionPerformed
        martes mar = new martes();
        mar.setVisible(true);
    }//GEN-LAST:event_btnmartesActionPerformed

    private void btnsabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsabadoActionPerformed
        // TODO add your handling code here:
        sabado sab = new sabado();
        sab.setVisible(true);
    }//GEN-LAST:event_btnsabadoActionPerformed

    private void btnmiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiercolesActionPerformed
        // TODO add your handling code here:
        miercoles mier = new miercoles();
        mier.setVisible(true);
    }//GEN-LAST:event_btnmiercolesActionPerformed

    private void btnlunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlunesActionPerformed
        // TODO add your handling code here:
        lunes lun = new lunes();
        lun.setVisible(true);
    }//GEN-LAST:event_btnlunesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlunes;
    private javax.swing.JButton btnmartes;
    private javax.swing.JButton btnmiercoles;
    private javax.swing.JButton btnsabado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
